name: Manual Deploy to Development

on:
  workflow_dispatch

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: deploy
        run: |
          echo "Development Deployment"
