name: Manual Deploy to Development

on:
  workflow_dispatch

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: integration
        run: |
          echo "Integration"
  deployment:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    environment: development # Environment の名前を指定
    needs: integration
    steps:
      - name: deploy
        run: |
          echo "Development Deployment"
