name: Manual Deploy to Development

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  test_step:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - run: echo "test_step Done."
