on: workflow_dispatch

env:
  MY_ENV_1: "Workflow Environment Variable 1"
  MY_ENV_2: "Workflow Environment Variable 2"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      # Workflow Environment Variable 1
      - run: echo ${{ env.MY_ENV_1 }}

      # Step Environment Variable 1
      - run: echo ${{ env.MY_ENV_1 }}
        env:
          MY_ENV_1: "Step Environment Variable 1"

  job2:
    runs-on: ubuntu-latest
    env:
      MY_ENV_1: "Job Environment Variable 1"
    steps:
      # Job Environment Variable 1
      - run: echo ${{ env.MY_ENV_1 }}

      # Workflow Environment Variable 2
      - run: echo ${{ env.MY_ENV_2 }}

      # Step Environment Variable 1
      - run: echo ${{ env.MY_ENV_1 }}
        env:
          MY_ENV_1: "Step Environment Variable 1"
